apiVersion: v1
kind: Pod
metadata:
  name: my-pod-hook
spec:
  containers:
  - name: container-1
    image: hook-test:dev
    lifecycle:
      postStart:  # ポッドのコンテナ開始時に実行
        exec:
          command: ["/bin/sh","-c", "echo postStart >> /app/app.log"]
      preStop:    # ポッドの終了要求で実行
        exec:
          command: ["/bin/sh","-c", "echo preStop >> /app/app.log; sleep 10"]
