apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods-high-priority
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-pod
  template: 
    metadata:     
      labels:
        app: my-pod
    spec:
      priorityClassName: high-priority  # プライオリティクラスの設定
      containers:
        - name: ubuntu
          image: ghcr.io/takara9/stress-ng:1.0
          command: ["/usr/bin/stress-ng", "--cpu", "2", "--malloc-bytes", "300M", "--malloc-zerofree"] 
          resources:
            requests:
              memory: "320M"
              cpu: 2  # ホストのコア数で調整
            limits:
              memory: "320M"
              cpu: 2  # 同上