apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
  - name: burstable-container
    image: ghcr.io/takara9/ex3:1.0
    resources:
      requests:
        memory: "200Mi"
        cpu: "700m"