apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - name: liveness
    image: ubuntu:latest
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; tail -f /dev/null
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      failureThreshold: 1  # 1回の失敗で再起動する
      terminationGracePeriodSeconds: 1 # SIGTERMを送ってからの猶予時間(秒)
      periodSeconds: 5 # 5秒間隔で診断する