## ビルドステージ
FROM maven:eclipse-temurin as build

# アプリケーションのインストール
COPY . /usr/src
WORKDIR /usr/src
RUN mvn -B package

##　実行ステージ
FROM eclipse-temurin:latest

## コンテナの設定
COPY --from=build --chown=65534:65534 /usr/src/target/rest-service-0.0.1.jar /app/app.jar
WORKDIR /app

ENV CLASSPATH /app/app.jar
ENTRYPOINT [ "" ]

USER 65534:65534
EXPOSE 8080
CMD ["java","-jar","/app/app.jar"]
