apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
  - name: readiness
    image: ubuntu:latest
    args:
    - /bin/sh
    - -c
    - sleep 15; touch /tmp/ready; tail -f /dev/null
    readinessProbe: # レディネスプローブ、デフォルト10秒間隔で実行
      exec:
        command: ["cat","/tmp/ready"]
