apiVersion: v1
kind: Pod
metadata:
  name: pod-cpu-constraints
spec:
  containers:
  - name: memory-constraints
    image: polinux/stress
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "500m"
    command: ["stress"]
    args: ["-c", "1"]


