apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:     
      labels:
        app: my-pod
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: ubuntu
          image: ghcr.io/takara9/ex1:1.1
  